/**
 * Localized content for the new-customer onboarding wizard.
 *
 * `en` is the source of truth. `type IntakeContent = typeof en` forces `pt` and `es`
 * to provide the exact same keys (the same safety the i18n dict gets from DeepStringify),
 * while keeping all three languages co-located so they never drift out of sync.
 */
import type { Locale } from "@/i18n/config";

const en = {
  eyebrow: "New Client Onboarding",
  title: "Let's build your marketing strategy",
  subtitle:
    "A few guided questions so our team can craft a strategy made for your business. Your progress saves automatically — leave and come back anytime.",
  nav: {
    next: "Continue",
    back: "Back",
    submit: "Submit & Get My Strategy",
    saving: "Saving…",
    saved: "Saved",
    saveError: "Couldn't save — check your connection",
    resumeTitle: "Welcome back!",
    resumeBody: "We saved your progress. Pick up where you left off?",
    resumeYes: "Continue where I left off",
    resumeNo: "Start over",
    step: "Step",
    of: "of",
    optional: "Optional",
    selectHint: "Select all that apply",
    yes: "Yes",
    no: "No",
    areaPrompt: "Enter your ZIP code and radius above to choose the areas you serve.",
    areaLoading: "Finding nearby areas…",
    areaAdd: "Add another area",
    areaDetected: "Detected",
    fileMaxNote: "That's the max of 5 uploads — drop the rest into a Google Drive folder and paste the link above.",
    addAnother: "Add another",
  },
  categories: [
    { id: "home_construction", label: "Home & Construction Trades" },
    { id: "food_restaurant", label: "Food & Restaurant" },
    { id: "retail_ecom", label: "Retail & E-commerce" },
    { id: "professional_services", label: "Professional Services" },
    { id: "health_wellness", label: "Health, Wellness & Beauty" },
    { id: "real_estate", label: "Real Estate" },
    { id: "faith_nonprofit", label: "Faith & Non-profit" },
    { id: "events", label: "Events & Entertainment" },
    { id: "other", label: "Something Else" },
  ],
  steps: [
    { id: "lead", title: "First, how can we reach you?", subtitle: "So we can follow up — even if you don't finish right now." },
    { id: "category", title: "What kind of business is this?", subtitle: "This tailors the rest of the questions to you." },
    { id: "name", title: "Your brand name", subtitle: "Let's start with what you're called." },
    { id: "general", title: "About the business", subtitle: "The essentials that shape your strategy." },
    { id: "owners", title: "About the owner(s)", subtitle: "People buy from people — tell us about you." },
    { id: "contact", title: "How we reach you", subtitle: "So we can follow up the right way." },
    { id: "presence", title: "What you have today", subtitle: "Your current footprint, online and off." },
    { id: "online", title: "Your online presence", subtitle: "Where customers find you now." },
    { id: "assets", title: "Photos, video & brand", subtitle: "Great visuals make great marketing." },
    { id: "deepdive", title: "A little deeper", subtitle: "A few questions specific to your industry." },
    { id: "goals", title: "Your goals", subtitle: "What winning looks like for you." },
    { id: "package", title: "The Complete Launch Package", subtitle: "Everything to launch your brand, done for you." },
    { id: "services", title: "How we can help", subtitle: "Pick what you're most interested in." },
    { id: "review", title: "Review & submit", subtitle: "Make sure everything looks right." },
  ],
  fields: {
    // ── name branch ──
    has_business_name: { label: "Do you already have a business name?" },
    business_name: { label: "Business name", placeholder: "Your Business LLC" },
    name_what: { label: "What does your business do?", placeholder: "e.g. custom steel railings and staircases for luxury homes" },
    name_audience: { label: "Who are your ideal customers?", placeholder: "e.g. high-end home builders and architects in the Boston area" },
    name_vibe: { label: "What feeling should the name give off?", options: ["Modern", "Luxury / Premium", "Friendly & Approachable", "Bold & Energetic", "Trustworthy & Established", "Playful & Fun", "Minimal & Clean"] },
    name_words_love: { label: "Words, themes, or values you'd love in the name", placeholder: "e.g. iron, craft, family, precision", help: "Optional — anything that feels like you" },
    name_words_avoid: { label: "Anything to avoid?", placeholder: "Words, styles, or names you don't want" },
    name_style: { label: "Preferred name style", options: ["Use my own name", "Descriptive (says what we do)", "Invented / unique word", "Location-based", "Open — surprise me"] },
    // ── general ──
    tagline: { label: "Tagline or slogan", placeholder: "If you have one" },
    business_stage: { label: "Where are you in the journey?", options: ["Just an idea", "Just launched (under 1 year)", "Established (1–5 years)", "Growing & scaling (5+ years)"] },
    employees: { label: "How many people work in the business?", options: ["Just me", "2–5", "6–10", "11–25", "25+"] },
    offer_home_construction: { label: "What products or services do you sell?", options: ["Kitchen remodeling", "Bathroom remodeling", "Additions & new builds", "Decks & patios", "Roofing", "Flooring", "Painting", "Windows & doors", "Steel & ironwork", "Railings & stairs", "Fences & gates", "Concrete & masonry", "Plumbing", "Electrical", "HVAC", "Handyman & repairs"] },
    offer_food_restaurant: { label: "What products or services do you sell?", options: ["Dine-in", "Takeout", "Delivery", "Catering", "Private events", "Bakery & desserts", "Coffee & drinks", "Bar & cocktails", "Meal prep", "Food truck"] },
    offer_retail_ecom: { label: "What products or services do you sell?", options: ["Clothing & apparel", "Shoes & accessories", "Jewelry", "Beauty & cosmetics", "Home & decor", "Electronics", "Food & beverage", "Handmade & crafts", "Health & supplements", "Pet products", "Kids & toys", "Other goods"] },
    offer_professional_services: { label: "What products or services do you sell?", options: ["Consulting", "Accounting & bookkeeping", "Legal services", "Marketing & advertising", "IT & tech support", "Coaching", "Insurance & financial", "Design & creative", "Photography & video", "Cleaning services", "Staffing & HR", "Education & tutoring"] },
    offer_health_wellness: { label: "What products or services do you sell?", options: ["Hair", "Nails", "Skincare & facials", "Massage", "Spa treatments", "Makeup", "Waxing", "Lashes & brows", "Med spa & injectables", "Fitness & training", "Yoga & pilates", "Nutrition", "Therapy & counseling", "Chiropractic", "Dental"] },
    offer_real_estate: { label: "What products or services do you sell?", options: ["Residential sales", "Commercial sales", "Rentals & leasing", "Property management", "Land & lots", "Luxury homes", "New construction", "Investment properties", "Relocation"] },
    offer_faith_nonprofit: { label: "What products or services do you sell?", options: ["Weekly services", "Bible study & groups", "Youth ministry", "Worship & music", "Community outreach", "Donations & giving", "Events & conferences", "Counseling", "Missions", "Volunteer programs"] },
    offer_events: { label: "What products or services do you sell?", options: ["Weddings", "Corporate events", "Concerts & shows", "Festivals", "Conferences", "Private parties", "Workshops", "Fundraisers", "Ticketed events"] },
    offer_other: { label: "What products or services do you sell?", placeholder: "Describe what you offer" },
    offerings: { label: "Anything else you sell?", placeholder: "Add anything not listed above" },
    usp: { label: "What makes you different from competitors?", placeholder: "Your edge, your story, what customers love" },
    service_zip: { label: "Your business ZIP code", placeholder: "e.g. 02145" },
    service_radius: { label: "How far do you serve customers?", options: ["Just my city / town", "Within 10 miles", "Within 25 miles", "Within 50 miles", "Within 100 miles", "Statewide", "Nationwide / online"] },
    service_areas: { label: "Specific areas, cities or counties you serve", placeholder: "e.g. Middlesex County, Somerville, Cambridge", help: "Optional — list the spots you want to focus on" },
    // ── owners ──
    contact_name: { label: "Your name", placeholder: "John Smith" },
    email: { label: "Your email", placeholder: "you@email.com" },
    owner_name: { label: "Owner's name (if different from you)", placeholder: "Full name" },
    owner_role: { label: "Your role / title", placeholder: "e.g. Founder & CEO" },
    owner_story: { label: "Why did you start this business?", placeholder: "Your story helps us tell it well" },
    owner_face: { label: "Do you want to be the face / personal brand of the business?" },
    languages: { label: "Which languages do you serve customers in?", options: ["English", "Spanish", "Portuguese", "Other"] },
    // ── contact ──
    business_email: { label: "Business email (if different from above)", placeholder: "hello@yourbusiness.com" },
    phone: { label: "Best phone number", placeholder: "(305) 555-0100" },
    preferred_contact: { label: "Preferred way to be contacted", options: ["Email", "Phone call", "Text / WhatsApp"] },
    hours: { label: "Business hours", placeholder: "e.g. Mon–Fri 8am–5pm" },
    // ── presence ──
    assets: { label: "Which of these does your business have?", options: ["Website", "Office", "Showroom", "Warehouse", "Fabrication shop", "Retail storefront", "Home-based", "Online only"] },
    locations_detail: { label: "Locations / addresses", placeholder: "Share the addresses of any physical locations" },
    // ── online ──
    website_url: { label: "Website address", placeholder: "https://" },
    website_feeling: { label: "How do you feel about your current website?", options: ["I love it", "It's okay", "It needs work", "I want a brand new one", "I don't have one yet"] },
    instagram: { label: "Instagram", placeholder: "@handle or link" },
    facebook: { label: "Facebook", placeholder: "Page name or link" },
    tiktok: { label: "TikTok", placeholder: "@handle or link" },
    youtube: { label: "YouTube", placeholder: "Channel link" },
    linkedin: { label: "LinkedIn", placeholder: "Profile or company link" },
    google_business: { label: "Google Business Profile", options: ["Yes — claimed & active", "Yes — but neglected", "No", "Not sure"] },
    reviews_status: { label: "Roughly how many reviews & what rating?", placeholder: "e.g. 45 reviews, 4.8 stars on Google" },
    social_logins: { label: "Social media logins (so we can post & manage for you)", options: ["Platform (e.g. Instagram)", "Email or username", "Password"], placeholder: "Add an account", help: "Optional & private — only if you'd like us to run your accounts for you. Stored securely and never shared." },
    // ── assets ──
    media_files: { label: "Upload photos or videos of your product / service", help: "Optional — drag & drop or browse" },
    media_links: { label: "Or paste links to your media", placeholder: "Google Drive, Dropbox, etc.", help: "💡 Tip: create one Google Drive folder, drop in ALL your business photos & videos, and paste the share link here. The more we have, the stronger your marketing." },
    logo_files: { label: "Upload your logo files", help: "Optional — PNG, SVG, AI, etc." },
    brand_colors: { label: "Brand colors", options: ["Main", "Secondary", "Accent", "Color 4", "Color 5"], placeholder: "Add color", help: "Optional — tap a swatch or paste your hex codes. No idea? We'll design a palette for you." },
    brand_fonts: { label: "Fonts you use", placeholder: "e.g. Montserrat, Georgia (optional)" },
    // ── deep dive: home_construction ──
    hc_project_types: { label: "What types of projects do you take on?", options: ["Residential", "Commercial", "New construction", "Renovations / remodels", "Repairs / service"] },
    hc_project_value: { label: "Typical project value", options: ["Under $1k", "$1k–$10k", "$10k–$50k", "$50k–$250k", "$250k+"] },
    hc_licensed: { label: "Are you licensed & insured?" },
    hc_radius: { label: "How far do you travel for work?", placeholder: "e.g. 50 miles from Somerville" },
    // ── deep dive: food_restaurant ──
    fr_cuisine: { label: "What kind of food do you serve?", placeholder: "e.g. wood-fired Italian" },
    fr_service: { label: "How do customers get your food?", options: ["Dine-in", "Takeout", "Delivery", "Catering", "Food truck"] },
    fr_menu_url: { label: "Link to your menu", placeholder: "https://" },
    fr_online_ordering: { label: "Do you offer online ordering?" },
    // ── deep dive: retail_ecom ──
    re_products: { label: "What products do you sell?", placeholder: "Your main categories" },
    re_platform: { label: "Where do you sell online?", options: ["Shopify", "WooCommerce", "Etsy", "Amazon", "Social media only", "Not online yet", "Other"] },
    re_aov: { label: "Average order value", options: ["Under $25", "$25–$75", "$75–$200", "$200+"] },
    re_instore: { label: "Do you also have a physical store?" },
    // ── deep dive: professional_services ──
    ps_services: { label: "What services do you offer?", placeholder: "List your main services" },
    ps_clients: { label: "Who are your clients?", options: ["Consumers (B2C)", "Businesses (B2B)", "Both"] },
    ps_appointments: { label: "Is your business appointment-based?" },
    ps_certs: { label: "Certifications or credentials", placeholder: "Anything that builds trust" },
    // ── deep dive: health_wellness ──
    hw_services: { label: "What treatments or services do you offer?", placeholder: "List your main offerings" },
    hw_booking: { label: "How do clients book?", options: ["Online booking system", "Call / text", "Walk-ins", "A mix"] },
    hw_practitioners: { label: "How many practitioners?", options: ["Just me", "2–5", "6–10", "10+"] },
    hw_memberships: { label: "Do you offer memberships or packages?" },
    // ── deep dive: real_estate ──
    rs_type: { label: "What do you focus on?", options: ["Residential", "Commercial", "Rentals", "Land", "Property management"] },
    rs_market: { label: "What market do you serve?", placeholder: "e.g. Miami-Dade luxury condos" },
    rs_brokerage: { label: "Brokerage / team name", placeholder: "If applicable" },
    // ── deep dive: faith_nonprofit ──
    fn_mission: { label: "What is your mission?", placeholder: "What you do and who you serve" },
    fn_size: { label: "How big is your community?", options: ["Under 50", "50–200", "200–500", "500–1,000", "1,000+"] },
    fn_events: { label: "Do you host regular events?" },
    fn_donations: { label: "Do you collect donations online?" },
    // ── deep dive: events ──
    ev_types: { label: "What kinds of events do you put on?", placeholder: "e.g. concerts, conferences, festivals" },
    ev_frequency: { label: "How often?", options: ["One-time", "Monthly", "Quarterly", "Yearly", "Ongoing / multiple"] },
    ev_ticketing: { label: "Do you sell tickets online?" },
    // ── deep dive: other ──
    ot_describe: { label: "Tell us about your business", placeholder: "Describe what you do so we can help" },
    // ── goals ──
    primary_goal: { label: "What's your #1 goal right now?", options: ["More leads & calls", "Brand awareness", "Online sales", "More foot traffic", "Rebrand / refresh", "Launch something new"] },
    ideal_customer: { label: "Describe your ideal customer", placeholder: "Who are they, where are they, what do they care about?" },
    budget: { label: "Monthly marketing budget", options: ["Not sure yet", "Under $1k", "$1k–$3k", "$3k–$5k", "$5k–$10k", "$10k+"] },
    current_marketing: { label: "What marketing are you doing now?", options: ["Nothing yet", "Social media", "Paid ads", "SEO", "Email", "Referrals / word of mouth"] },
    challenge_options: { label: "What's your biggest challenge right now?", options: ["Not enough leads or calls", "Inconsistent sales", "Low brand awareness", "Weak online presence", "Outdated or no website", "Not showing up on Google", "Losing to competitors", "No repeat customers", "Pricing & profit margins", "Hiring & staffing", "Scaling & growth", "Reviews & reputation"] },
    biggest_challenge: { label: "Anything else holding you back?", placeholder: "Add it in your own words (optional)" },
    competitors: { label: "Competitors you admire", placeholder: "Name or link", help: "Add up to 5 — helps us benchmark" },
    timeline: { label: "How soon do you want to start?", options: ["ASAP", "1–3 months", "3–6 months", "Just exploring"] },
    success_options: { label: "What does success look like in 6 months?", options: ["Double my leads", "Consistent monthly sales", "Fully booked schedule", "A brand people recognize", "#1 on Google in my area", "More 5-star reviews", "A growing social following", "Launched something new", "Hired more team members", "Opened a new location", "Marketing that runs itself", "More time freedom"] },
    success_vision: { label: "Anything else? Describe your dream outcome", placeholder: "Paint us the picture (optional)" },
    // ── services ──
    services_interested: { label: "What are you most interested in?", options: ["Branding & Logo", "Website", "Paid Ads", "Social Media", "SEO", "CRM & Automation", "Business Mentorship", "Mobile App"] },
    anything_else: { label: "Anything else we should know?", placeholder: "Optional — the floor is yours" },
    // ── launch package ──
    want_package: { label: "Want us to handle your entire launch in one package?" },
    pkg_colors: { label: "Brand colors you'd like", placeholder: "e.g. navy & gold — or 'help me choose'" },
    pkg_logo_have: { label: "Do you already have a logo you love?" },
    pkg_logo_files: { label: "Upload your logo or any inspiration", help: "Optional — current logo, sketches, or styles you like" },
    pkg_logo_likes: { label: "Logos or brands whose look you admire", placeholder: "Names or links — helps us nail the style" },
    pkg_instagram_handle: { label: "Instagram handle you'd like", placeholder: "@yourbusiness (we'll check availability)" },
    pkg_domain: { label: "Website domain you'd like", placeholder: "yourbusiness.com" },
    pkg_cards_people: { label: "Who needs a business card?", placeholder: "Add person", help: "Add each owner or employee who needs a card", options: ["Name", "Title / Role", "Phone", "Email"] },
  },
  review: {
    title: "Almost done!",
    subtitle: "Here's everything you shared. Tap any step to edit.",
    consent: "I agree to be contacted by 360 For Business about my marketing strategy.",
    edit: "Edit",
    empty: "Not answered",
  },
  done: {
    title: "Thank you — we've got it!",
    body: "Thank you for sending us your form! Our team is already working on your custom marketing strategy — we'll be in touch within 24 to 48 hours.",
    cta: "Back to home",
  },
  package: {
    introTitle: "Everything you need to launch — done for you",
    introBody: "One package, one team, one cohesive brand. Here's what's included:",
    includes: [
      "Professional Website",
      "Instagram Setup & Branding",
      "360 CRM & Automation",
      "Logo Design",
      "Full Brand Identity",
      "Business Cards for Your Team",
    ],
    addPerson: "Add another person",
  },
} satisfies IntakeContentShape;

// Shape guard so `en` itself is checked; `IntakeContent` (below) is what pt/es must match.
type IntakeContentShape = {
  eyebrow: string;
  title: string;
  subtitle: string;
  nav: Record<string, string>;
  categories: { id: string; label: string }[];
  steps: { id: string; title: string; subtitle?: string }[];
  fields: Record<string, { label: string; placeholder?: string; help?: string; options?: string[] }>;
  review: Record<string, string>;
  done: Record<string, string>;
  package: {
    introTitle: string;
    introBody: string;
    includes: string[];
    addPerson: string;
  };
};

export type IntakeContent = typeof en;

const pt: IntakeContent = {
  eyebrow: "Cadastro de Novo Cliente",
  title: "Vamos construir sua estratégia de marketing",
  subtitle:
    "Algumas perguntas guiadas para nossa equipe criar uma estratégia feita para o seu negócio. Seu progresso é salvo automaticamente — saia e volte quando quiser.",
  nav: {
    next: "Continuar",
    back: "Voltar",
    submit: "Enviar & Receber Minha Estratégia",
    saving: "Salvando…",
    saved: "Salvo",
    saveError: "Não foi possível salvar — verifique sua conexão",
    resumeTitle: "Bem-vindo de volta!",
    resumeBody: "Salvamos seu progresso. Continuar de onde parou?",
    resumeYes: "Continuar de onde parei",
    resumeNo: "Começar do zero",
    step: "Etapa",
    of: "de",
    optional: "Opcional",
    selectHint: "Selecione todas as opções aplicáveis",
    yes: "Sim",
    no: "Não",
    areaPrompt: "Digite seu código postal (ZIP) e o raio acima para escolher as áreas que você atende.",
    areaLoading: "Buscando áreas próximas…",
    areaAdd: "Adicionar outra área",
    areaDetected: "Detectado",
    fileMaxNote: "Esse é o máximo de 5 arquivos — coloque o restante em uma pasta do Google Drive e cole o link acima.",
    addAnother: "Adicionar outro",
  },
  categories: [
    { id: "home_construction", label: "Construção & Reformas" },
    { id: "food_restaurant", label: "Alimentação & Restaurante" },
    { id: "retail_ecom", label: "Varejo & E-commerce" },
    { id: "professional_services", label: "Serviços Profissionais" },
    { id: "health_wellness", label: "Saúde, Bem-estar & Beleza" },
    { id: "real_estate", label: "Imobiliário" },
    { id: "faith_nonprofit", label: "Igreja & Sem Fins Lucrativos" },
    { id: "events", label: "Eventos & Entretenimento" },
    { id: "other", label: "Outro Segmento" },
  ],
  steps: [
    { id: "lead", title: "Primeiro, como podemos falar com você?", subtitle: "Para darmos retorno — mesmo se você não terminar agora." },
    { id: "category", title: "Que tipo de negócio é esse?", subtitle: "Isso personaliza as próximas perguntas para você." },
    { id: "name", title: "O nome da sua marca", subtitle: "Vamos começar pelo seu nome." },
    { id: "general", title: "Sobre o negócio", subtitle: "O essencial que molda sua estratégia." },
    { id: "owners", title: "Sobre o(s) dono(s)", subtitle: "Pessoas compram de pessoas — conte sobre você." },
    { id: "contact", title: "Como falar com você", subtitle: "Para darmos o retorno do jeito certo." },
    { id: "presence", title: "O que você já tem hoje", subtitle: "Sua presença atual, online e offline." },
    { id: "online", title: "Sua presença online", subtitle: "Onde os clientes te encontram hoje." },
    { id: "assets", title: "Fotos, vídeo & marca", subtitle: "Bons visuais fazem bom marketing." },
    { id: "deepdive", title: "Um pouco mais fundo", subtitle: "Algumas perguntas específicas do seu setor." },
    { id: "goals", title: "Seus objetivos", subtitle: "O que é vencer para você." },
    { id: "package", title: "O Pacote Completo de Lançamento", subtitle: "Tudo para lançar sua marca, feito para você." },
    { id: "services", title: "Como podemos ajudar", subtitle: "Escolha o que mais te interessa." },
    { id: "review", title: "Revisar & enviar", subtitle: "Confira se está tudo certo." },
  ],
  fields: {
    has_business_name: { label: "Você já tem um nome para o negócio?" },
    business_name: { label: "Nome do negócio", placeholder: "Seu Negócio LTDA" },
    name_what: { label: "O que o seu negócio faz?", placeholder: "ex. corrimãos e escadas de aço sob medida para casas de alto padrão" },
    name_audience: { label: "Quem são seus clientes ideais?", placeholder: "ex. construtoras e arquitetos de alto padrão em Boston" },
    name_vibe: { label: "Que sensação o nome deve passar?", options: ["Moderno", "Luxo / Premium", "Amigável & Acessível", "Ousado & Energético", "Confiável & Consolidado", "Divertido & Leve", "Minimalista & Limpo"] },
    name_words_love: { label: "Palavras, temas ou valores que você gostaria no nome", placeholder: "ex. ferro, ofício, família, precisão", help: "Opcional — qualquer coisa com a sua cara" },
    name_words_avoid: { label: "Algo a evitar?", placeholder: "Palavras, estilos ou nomes que você não quer" },
    name_style: { label: "Estilo de nome preferido", options: ["Usar meu próprio nome", "Descritivo (diz o que fazemos)", "Inventado / único", "Baseado na localização", "Aberto — me surpreenda"] },
    tagline: { label: "Slogan ou frase", placeholder: "Se você tiver um" },
    business_stage: { label: "Em que fase você está?", options: ["Só uma ideia", "Recém-lançado (menos de 1 ano)", "Estabelecido (1–5 anos)", "Crescendo & escalando (5+ anos)"] },
    employees: { label: "Quantas pessoas trabalham no negócio?", options: ["Só eu", "2–5", "6–10", "11–25", "25+"] },
    offer_home_construction: { label: "Quais produtos ou serviços você vende?", options: ["Reforma de cozinha", "Reforma de banheiro", "Ampliações & obras novas", "Decks & varandas", "Telhados", "Pisos", "Pintura", "Janelas & portas", "Aço & serralheria", "Corrimãos & escadas", "Cercas & portões", "Concreto & alvenaria", "Encanamento", "Elétrica", "Ar-condicionado", "Reparos gerais"] },
    offer_food_restaurant: { label: "Quais produtos ou serviços você vende?", options: ["No local", "Retirada", "Delivery", "Buffet / catering", "Eventos privados", "Padaria & sobremesas", "Café & bebidas", "Bar & coquetéis", "Marmitas", "Food truck"] },
    offer_retail_ecom: { label: "Quais produtos ou serviços você vende?", options: ["Roupas & moda", "Calçados & acessórios", "Joias", "Beleza & cosméticos", "Casa & decoração", "Eletrônicos", "Alimentos & bebidas", "Artesanato", "Saúde & suplementos", "Produtos pet", "Infantil & brinquedos", "Outros produtos"] },
    offer_professional_services: { label: "Quais produtos ou serviços você vende?", options: ["Consultoria", "Contabilidade", "Serviços jurídicos", "Marketing & publicidade", "TI & suporte técnico", "Coaching", "Seguros & financeiro", "Design & criação", "Fotografia & vídeo", "Limpeza", "Recrutamento & RH", "Educação & aulas"] },
    offer_health_wellness: { label: "Quais produtos ou serviços você vende?", options: ["Cabelo", "Unhas", "Skincare & limpeza de pele", "Massagem", "Tratamentos de spa", "Maquiagem", "Depilação", "Cílios & sobrancelhas", "Estética avançada & injetáveis", "Fitness & treino", "Yoga & pilates", "Nutrição", "Terapia & aconselhamento", "Quiropraxia", "Odontologia"] },
    offer_real_estate: { label: "Quais produtos ou serviços você vende?", options: ["Vendas residenciais", "Vendas comerciais", "Locação", "Administração de imóveis", "Terrenos & lotes", "Imóveis de luxo", "Construção nova", "Imóveis de investimento", "Realocação"] },
    offer_faith_nonprofit: { label: "Quais produtos ou serviços você vende?", options: ["Cultos semanais", "Estudos bíblicos & grupos", "Ministério jovem", "Louvor & música", "Ação social", "Doações & contribuições", "Eventos & conferências", "Aconselhamento", "Missões", "Programas de voluntariado"] },
    offer_events: { label: "Quais produtos ou serviços você vende?", options: ["Casamentos", "Eventos corporativos", "Shows & concertos", "Festivais", "Conferências", "Festas privadas", "Workshops", "Arrecadações", "Eventos com ingressos"] },
    offer_other: { label: "Quais produtos ou serviços você vende?", placeholder: "Descreva o que você oferece" },
    offerings: { label: "Mais alguma coisa que você vende?", placeholder: "Adicione o que não está na lista acima" },
    usp: { label: "O que te diferencia dos concorrentes?", placeholder: "Seu diferencial, sua história, o que os clientes amam" },
    service_zip: { label: "Código postal (ZIP) do seu negócio", placeholder: "ex. 02145" },
    service_radius: { label: "Até onde você atende clientes?", options: ["Só minha cidade", "Até 10 milhas", "Até 25 milhas", "Até 50 milhas", "Até 100 milhas", "Estado inteiro", "País todo / online"] },
    service_areas: { label: "Áreas, cidades ou condados específicos que você atende", placeholder: "ex. Middlesex County, Somerville, Cambridge", help: "Opcional — liste os lugares em que quer focar" },
    contact_name: { label: "Seu nome", placeholder: "João Silva" },
    email: { label: "Seu e-mail", placeholder: "voce@email.com" },
    owner_name: { label: "Nome do dono (se for outra pessoa)", placeholder: "Nome completo" },
    owner_role: { label: "Seu cargo / função", placeholder: "ex. Fundador & CEO" },
    owner_story: { label: "Por que você começou esse negócio?", placeholder: "Sua história ajuda a contá-la bem" },
    owner_face: { label: "Você quer ser o rosto / marca pessoal do negócio?" },
    languages: { label: "Em quais idiomas você atende clientes?", options: ["Inglês", "Espanhol", "Português", "Outro"] },
    business_email: { label: "E-mail comercial (se for diferente)", placeholder: "contato@seunegocio.com" },
    phone: { label: "Melhor telefone", placeholder: "(305) 555-0100" },
    preferred_contact: { label: "Forma preferida de contato", options: ["E-mail", "Ligação", "Texto / WhatsApp"] },
    hours: { label: "Horário de funcionamento", placeholder: "ex. Seg–Sex 8h–17h" },
    assets: { label: "Quais destes o seu negócio tem?", options: ["Site", "Escritório", "Showroom", "Depósito", "Oficina / fabricação", "Loja física", "Em casa", "Somente online"] },
    locations_detail: { label: "Locais / endereços", placeholder: "Compartilhe os endereços dos locais físicos" },
    website_url: { label: "Endereço do site", placeholder: "https://" },
    website_feeling: { label: "Como você se sente sobre seu site atual?", options: ["Eu amo", "Está ok", "Precisa melhorar", "Quero um novo", "Ainda não tenho"] },
    instagram: { label: "Instagram", placeholder: "@perfil ou link" },
    facebook: { label: "Facebook", placeholder: "Nome da página ou link" },
    tiktok: { label: "TikTok", placeholder: "@perfil ou link" },
    youtube: { label: "YouTube", placeholder: "Link do canal" },
    linkedin: { label: "LinkedIn", placeholder: "Perfil ou link da empresa" },
    google_business: { label: "Perfil da Empresa no Google", options: ["Sim — reivindicado & ativo", "Sim — mas abandonado", "Não", "Não sei"] },
    reviews_status: { label: "Mais ou menos quantas avaliações & qual nota?", placeholder: "ex. 45 avaliações, 4,8 estrelas no Google" },
    social_logins: { label: "Logins das redes sociais (para a gente postar & gerenciar para você)", options: ["Plataforma (ex. Instagram)", "E-mail ou usuário", "Senha"], placeholder: "Adicionar uma conta", help: "Opcional & privado — só se você quiser que a gente cuide das suas contas. Guardado com segurança e nunca compartilhado." },
    media_files: { label: "Envie fotos ou vídeos do seu produto / serviço", help: "Opcional — arraste & solte ou procure" },
    media_links: { label: "Ou cole links da sua mídia", placeholder: "Google Drive, Dropbox, etc.", help: "💡 Dica: crie uma pasta no Google Drive, coloque TODAS as fotos e vídeos do seu negócio e cole o link de compartilhamento aqui. Quanto mais tivermos, mais forte fica o seu marketing." },
    logo_files: { label: "Envie os arquivos do seu logo", help: "Opcional — PNG, SVG, AI, etc." },
    brand_colors: { label: "Cores da marca", options: ["Principal", "Secundária", "Destaque", "Cor 4", "Cor 5"], placeholder: "Adicionar cor", help: "Opcional — toque em um quadrado ou cole seus códigos hex. Não sabe? A gente cria a paleta para você." },
    brand_fonts: { label: "Fontes que você usa", placeholder: "ex. Montserrat, Georgia (opcional)" },
    hc_project_types: { label: "Que tipos de projeto você faz?", options: ["Residencial", "Comercial", "Construção nova", "Reformas", "Reparos / manutenção"] },
    hc_project_value: { label: "Valor típico de um projeto", options: ["Menos de $1k", "$1k–$10k", "$10k–$50k", "$50k–$250k", "$250k+"] },
    hc_licensed: { label: "Você é licenciado & segurado?" },
    hc_radius: { label: "Até onde você vai para trabalhar?", placeholder: "ex. 80 km de Somerville" },
    fr_cuisine: { label: "Que tipo de comida você serve?", placeholder: "ex. italiana na lenha" },
    fr_service: { label: "Como os clientes recebem sua comida?", options: ["No local", "Retirada", "Delivery", "Buffet / catering", "Food truck"] },
    fr_menu_url: { label: "Link do seu cardápio", placeholder: "https://" },
    fr_online_ordering: { label: "Você oferece pedidos online?" },
    re_products: { label: "Quais produtos você vende?", placeholder: "Suas principais categorias" },
    re_platform: { label: "Onde você vende online?", options: ["Shopify", "WooCommerce", "Etsy", "Amazon", "Só redes sociais", "Ainda não vendo online", "Outro"] },
    re_aov: { label: "Ticket médio do pedido", options: ["Menos de $25", "$25–$75", "$75–$200", "$200+"] },
    re_instore: { label: "Você também tem loja física?" },
    ps_services: { label: "Quais serviços você oferece?", placeholder: "Liste seus principais serviços" },
    ps_clients: { label: "Quem são seus clientes?", options: ["Consumidores (B2C)", "Empresas (B2B)", "Ambos"] },
    ps_appointments: { label: "Seu negócio funciona com agendamento?" },
    ps_certs: { label: "Certificações ou credenciais", placeholder: "Algo que gera confiança" },
    hw_services: { label: "Quais tratamentos ou serviços você oferece?", placeholder: "Liste suas principais ofertas" },
    hw_booking: { label: "Como os clientes agendam?", options: ["Sistema de agendamento online", "Ligação / texto", "Sem hora marcada", "Uma mistura"] },
    hw_practitioners: { label: "Quantos profissionais?", options: ["Só eu", "2–5", "6–10", "10+"] },
    hw_memberships: { label: "Você oferece planos ou pacotes?" },
    rs_type: { label: "Qual é o seu foco?", options: ["Residencial", "Comercial", "Locação", "Terrenos", "Administração de imóveis"] },
    rs_market: { label: "Qual mercado você atende?", placeholder: "ex. apartamentos de luxo em Miami-Dade" },
    rs_brokerage: { label: "Nome da imobiliária / equipe", placeholder: "Se aplicável" },
    fn_mission: { label: "Qual é a sua missão?", placeholder: "O que você faz e quem atende" },
    fn_size: { label: "Qual o tamanho da sua comunidade?", options: ["Menos de 50", "50–200", "200–500", "500–1.000", "1.000+"] },
    fn_events: { label: "Você realiza eventos regularmente?" },
    fn_donations: { label: "Você recebe doações online?" },
    ev_types: { label: "Que tipos de evento você organiza?", placeholder: "ex. shows, conferências, festivais" },
    ev_frequency: { label: "Com que frequência?", options: ["Único", "Mensal", "Trimestral", "Anual", "Contínuo / vários"] },
    ev_ticketing: { label: "Você vende ingressos online?" },
    ot_describe: { label: "Conte sobre o seu negócio", placeholder: "Descreva o que você faz para podermos ajudar" },
    primary_goal: { label: "Qual é o seu objetivo nº 1 agora?", options: ["Mais leads & ligações", "Reconhecimento de marca", "Vendas online", "Mais movimento na loja", "Rebrand / renovação", "Lançar algo novo"] },
    ideal_customer: { label: "Descreva seu cliente ideal", placeholder: "Quem são, onde estão, com o que se importam?" },
    budget: { label: "Orçamento mensal de marketing", options: ["Ainda não sei", "Menos de $1k", "$1k–$3k", "$3k–$5k", "$5k–$10k", "$10k+"] },
    current_marketing: { label: "Que marketing você faz hoje?", options: ["Nada ainda", "Redes sociais", "Anúncios pagos", "SEO", "E-mail", "Indicações / boca a boca"] },
    challenge_options: { label: "Qual é o seu maior desafio agora?", options: ["Poucos leads ou ligações", "Vendas inconsistentes", "Pouco reconhecimento de marca", "Presença online fraca", "Site desatualizado ou inexistente", "Não aparece no Google", "Perdendo para concorrentes", "Sem clientes recorrentes", "Preços & margens de lucro", "Contratação & equipe", "Crescimento & escala", "Avaliações & reputação"] },
    biggest_challenge: { label: "Mais alguma coisa te travando?", placeholder: "Conte com suas palavras (opcional)" },
    competitors: { label: "Concorrentes que você admira", placeholder: "Nome ou link", help: "Adicione até 5 — ajuda a comparar" },
    timeline: { label: "Quando você quer começar?", options: ["O quanto antes", "1–3 meses", "3–6 meses", "Só explorando"] },
    success_options: { label: "Como é o sucesso em 6 meses?", options: ["Dobrar meus leads", "Vendas mensais consistentes", "Agenda lotada", "Uma marca reconhecida", "Nº 1 no Google da minha região", "Mais avaliações 5 estrelas", "Seguidores crescendo", "Lançar algo novo", "Contratar mais gente", "Abrir um novo local", "Marketing no automático", "Mais tempo livre"] },
    success_vision: { label: "Mais alguma coisa? Descreva o resultado dos sonhos", placeholder: "Descreva o cenário ideal (opcional)" },
    services_interested: { label: "No que você tem mais interesse?", options: ["Marca & Logo", "Site", "Anúncios Pagos", "Redes Sociais", "SEO", "CRM & Automação", "Mentoria de Negócio", "Aplicativo"] },
    anything_else: { label: "Mais alguma coisa que devemos saber?", placeholder: "Opcional — fique à vontade" },
    // ── pacote de lançamento ──
    want_package: { label: "Quer que a gente cuide do seu lançamento inteiro em um pacote só?" },
    pkg_colors: { label: "Cores de marca que você gostaria", placeholder: "ex. azul-marinho & dourado — ou 'me ajude a escolher'" },
    pkg_logo_have: { label: "Você já tem um logo que ama?" },
    pkg_logo_files: { label: "Envie seu logo ou inspirações", help: "Opcional — logo atual, rascunhos ou estilos que você gosta" },
    pkg_logo_likes: { label: "Logos ou marcas com um visual que você admira", placeholder: "Nomes ou links — ajuda a acertar o estilo" },
    pkg_instagram_handle: { label: "@ do Instagram que você gostaria", placeholder: "@seunegocio (vamos checar a disponibilidade)" },
    pkg_domain: { label: "Domínio do site que você gostaria", placeholder: "seunegocio.com" },
    pkg_cards_people: { label: "Quem precisa de cartão de visita?", placeholder: "Adicionar pessoa", help: "Adicione cada dono ou funcionário que precisa de cartão", options: ["Nome", "Cargo / Função", "Telefone", "E-mail"] },
  },
  review: {
    title: "Quase lá!",
    subtitle: "Aqui está tudo o que você compartilhou. Toque em qualquer etapa para editar.",
    consent: "Concordo em ser contatado pela 360 For Business sobre minha estratégia de marketing.",
    edit: "Editar",
    empty: "Não respondido",
  },
  done: {
    title: "Obrigado — recebemos tudo!",
    body: "Nossa equipe está analisando suas respostas e entrará em contato em até 24 horas com a primeira prévia da sua estratégia de marketing personalizada.",
    cta: "Voltar ao início",
  },
  package: {
    introTitle: "Tudo o que você precisa para lançar — feito para você",
    introBody: "Um pacote, uma equipe, uma marca coesa. Veja o que está incluído:",
    includes: [
      "Site Profissional",
      "Configuração & Branding do Instagram",
      "CRM & Automação 360",
      "Criação de Logo",
      "Identidade de Marca Completa",
      "Cartões de Visita para a Sua Equipe",
    ],
    addPerson: "Adicionar outra pessoa",
  },
};

const es: IntakeContent = {
  eyebrow: "Registro de Nuevo Cliente",
  title: "Construyamos tu estrategia de marketing",
  subtitle:
    "Unas preguntas guiadas para que nuestro equipo cree una estrategia hecha para tu negocio. Tu progreso se guarda automáticamente — sal y regresa cuando quieras.",
  nav: {
    next: "Continuar",
    back: "Atrás",
    submit: "Enviar & Recibir Mi Estrategia",
    saving: "Guardando…",
    saved: "Guardado",
    saveError: "No se pudo guardar — revisa tu conexión",
    resumeTitle: "¡Bienvenido de nuevo!",
    resumeBody: "Guardamos tu progreso. ¿Continuar donde lo dejaste?",
    resumeYes: "Continuar donde lo dejé",
    resumeNo: "Empezar de nuevo",
    step: "Paso",
    of: "de",
    optional: "Opcional",
    selectHint: "Selecciona todas las que apliquen",
    yes: "Sí",
    no: "No",
    areaPrompt: "Ingresa tu código postal (ZIP) y el radio arriba para elegir las áreas que atiendes.",
    areaLoading: "Buscando áreas cercanas…",
    areaAdd: "Agregar otra área",
    areaDetected: "Detectado",
    fileMaxNote: "Ese es el máximo de 5 archivos — sube el resto a una carpeta de Google Drive y pega el enlace arriba.",
    addAnother: "Agregar otro",
  },
  categories: [
    { id: "home_construction", label: "Construcción & Remodelación" },
    { id: "food_restaurant", label: "Comida & Restaurante" },
    { id: "retail_ecom", label: "Retail & E-commerce" },
    { id: "professional_services", label: "Servicios Profesionales" },
    { id: "health_wellness", label: "Salud, Bienestar & Belleza" },
    { id: "real_estate", label: "Bienes Raíces" },
    { id: "faith_nonprofit", label: "Iglesia & Sin Fines de Lucro" },
    { id: "events", label: "Eventos & Entretenimiento" },
    { id: "other", label: "Otro Rubro" },
  ],
  steps: [
    { id: "lead", title: "Primero, ¿cómo te contactamos?", subtitle: "Para darte seguimiento — aunque no termines ahora." },
    { id: "category", title: "¿Qué tipo de negocio es?", subtitle: "Esto adapta las siguientes preguntas a ti." },
    { id: "name", title: "El nombre de tu marca", subtitle: "Empecemos por cómo te llamas." },
    { id: "general", title: "Sobre el negocio", subtitle: "Lo esencial que da forma a tu estrategia." },
    { id: "owners", title: "Sobre el/los dueño(s)", subtitle: "La gente le compra a la gente — cuéntanos de ti." },
    { id: "contact", title: "Cómo contactarte", subtitle: "Para darte seguimiento de la forma correcta." },
    { id: "presence", title: "Lo que ya tienes hoy", subtitle: "Tu presencia actual, online y offline." },
    { id: "online", title: "Tu presencia online", subtitle: "Dónde te encuentran los clientes ahora." },
    { id: "assets", title: "Fotos, video & marca", subtitle: "Buen contenido visual hace buen marketing." },
    { id: "deepdive", title: "Un poco más a fondo", subtitle: "Unas preguntas específicas de tu industria." },
    { id: "goals", title: "Tus objetivos", subtitle: "Cómo se ve ganar para ti." },
    { id: "package", title: "El Paquete Completo de Lanzamiento", subtitle: "Todo para lanzar tu marca, hecho por nosotros." },
    { id: "services", title: "Cómo podemos ayudar", subtitle: "Elige lo que más te interesa." },
    { id: "review", title: "Revisar & enviar", subtitle: "Asegúrate de que todo esté bien." },
  ],
  fields: {
    has_business_name: { label: "¿Ya tienes un nombre para el negocio?" },
    business_name: { label: "Nombre del negocio", placeholder: "Tu Negocio LLC" },
    name_what: { label: "¿Qué hace tu negocio?", placeholder: "ej. barandas y escaleras de acero a medida para casas de lujo" },
    name_audience: { label: "¿Quiénes son tus clientes ideales?", placeholder: "ej. constructoras y arquitectos de lujo en Boston" },
    name_vibe: { label: "¿Qué sensación debe dar el nombre?", options: ["Moderno", "Lujo / Premium", "Amigable & Cercano", "Audaz & Enérgico", "Confiable & Consolidado", "Divertido & Ligero", "Minimalista & Limpio"] },
    name_words_love: { label: "Palabras, temas o valores que te gustaría en el nombre", placeholder: "ej. hierro, oficio, familia, precisión", help: "Opcional — lo que sienta tuyo" },
    name_words_avoid: { label: "¿Algo a evitar?", placeholder: "Palabras, estilos o nombres que no quieres" },
    name_style: { label: "Estilo de nombre preferido", options: ["Usar mi propio nombre", "Descriptivo (dice lo que hacemos)", "Inventado / único", "Basado en la ubicación", "Abierto — sorpréndeme"] },
    tagline: { label: "Eslogan o frase", placeholder: "Si tienes uno" },
    business_stage: { label: "¿En qué etapa estás?", options: ["Solo una idea", "Recién lanzado (menos de 1 año)", "Establecido (1–5 años)", "Creciendo & escalando (5+ años)"] },
    employees: { label: "¿Cuántas personas trabajan en el negocio?", options: ["Solo yo", "2–5", "6–10", "11–25", "25+"] },
    offer_home_construction: { label: "¿Qué productos o servicios vendes?", options: ["Remodelación de cocina", "Remodelación de baño", "Ampliaciones & obra nueva", "Terrazas & patios", "Techos", "Pisos", "Pintura", "Ventanas & puertas", "Acero & herrería", "Barandas & escaleras", "Cercas & portones", "Concreto & albañilería", "Plomería", "Electricidad", "Aire acondicionado", "Reparaciones generales"] },
    offer_food_restaurant: { label: "¿Qué productos o servicios vendes?", options: ["En el local", "Para llevar", "Delivery", "Catering", "Eventos privados", "Panadería & postres", "Café & bebidas", "Bar & cócteles", "Comida preparada", "Food truck"] },
    offer_retail_ecom: { label: "¿Qué productos o servicios vendes?", options: ["Ropa & moda", "Calzado & accesorios", "Joyería", "Belleza & cosméticos", "Hogar & decoración", "Electrónica", "Alimentos & bebidas", "Hecho a mano & artesanía", "Salud & suplementos", "Productos para mascotas", "Niños & juguetes", "Otros productos"] },
    offer_professional_services: { label: "¿Qué productos o servicios vendes?", options: ["Consultoría", "Contabilidad", "Servicios legales", "Marketing & publicidad", "TI & soporte técnico", "Coaching", "Seguros & finanzas", "Diseño & creatividad", "Fotografía & video", "Limpieza", "Reclutamiento & RRHH", "Educación & tutorías"] },
    offer_health_wellness: { label: "¿Qué productos o servicios vendes?", options: ["Cabello", "Uñas", "Cuidado de la piel & faciales", "Masajes", "Tratamientos de spa", "Maquillaje", "Depilación", "Pestañas & cejas", "Medicina estética & inyectables", "Fitness & entrenamiento", "Yoga & pilates", "Nutrición", "Terapia & consejería", "Quiropráctica", "Odontología"] },
    offer_real_estate: { label: "¿Qué productos o servicios vendes?", options: ["Ventas residenciales", "Ventas comerciales", "Alquileres", "Administración de propiedades", "Terrenos & lotes", "Casas de lujo", "Obra nueva", "Propiedades de inversión", "Reubicación"] },
    offer_faith_nonprofit: { label: "¿Qué productos o servicios vendes?", options: ["Servicios semanales", "Estudios bíblicos & grupos", "Ministerio juvenil", "Alabanza & música", "Acción comunitaria", "Donaciones & ofrendas", "Eventos & conferencias", "Consejería", "Misiones", "Programas de voluntariado"] },
    offer_events: { label: "¿Qué productos o servicios vendes?", options: ["Bodas", "Eventos corporativos", "Conciertos & shows", "Festivales", "Conferencias", "Fiestas privadas", "Talleres", "Recaudaciones", "Eventos con boletos"] },
    offer_other: { label: "¿Qué productos o servicios vendes?", placeholder: "Describe lo que ofreces" },
    offerings: { label: "¿Algo más que vendas?", placeholder: "Agrega lo que no esté en la lista de arriba" },
    usp: { label: "¿Qué te diferencia de la competencia?", placeholder: "Tu ventaja, tu historia, lo que aman los clientes" },
    service_zip: { label: "Código postal (ZIP) de tu negocio", placeholder: "ej. 02145" },
    service_radius: { label: "¿Hasta dónde atiendes a tus clientes?", options: ["Solo mi ciudad", "Hasta 10 millas", "Hasta 25 millas", "Hasta 50 millas", "Hasta 100 millas", "Todo el estado", "Todo el país / en línea"] },
    service_areas: { label: "Áreas, ciudades o condados específicos que atiendes", placeholder: "ej. Middlesex County, Somerville, Cambridge", help: "Opcional — enumera los lugares en los que quieres enfocarte" },
    contact_name: { label: "Tu nombre", placeholder: "Juan Pérez" },
    email: { label: "Tu correo", placeholder: "tu@correo.com" },
    owner_name: { label: "Nombre del dueño (si es otra persona)", placeholder: "Nombre completo" },
    owner_role: { label: "Tu cargo / rol", placeholder: "ej. Fundador & CEO" },
    owner_story: { label: "¿Por qué empezaste este negocio?", placeholder: "Tu historia nos ayuda a contarla bien" },
    owner_face: { label: "¿Quieres ser la cara / marca personal del negocio?" },
    languages: { label: "¿En qué idiomas atiendes a tus clientes?", options: ["Inglés", "Español", "Portugués", "Otro"] },
    business_email: { label: "Correo comercial (si es diferente)", placeholder: "hola@tunegocio.com" },
    phone: { label: "Mejor teléfono", placeholder: "(305) 555-0100" },
    preferred_contact: { label: "Forma preferida de contacto", options: ["Correo", "Llamada", "Texto / WhatsApp"] },
    hours: { label: "Horario de atención", placeholder: "ej. Lun–Vie 8am–5pm" },
    assets: { label: "¿Cuáles de estos tiene tu negocio?", options: ["Sitio web", "Oficina", "Showroom", "Bodega", "Taller / fabricación", "Local físico", "Desde casa", "Solo online"] },
    locations_detail: { label: "Ubicaciones / direcciones", placeholder: "Comparte las direcciones de tus locales físicos" },
    website_url: { label: "Dirección del sitio web", placeholder: "https://" },
    website_feeling: { label: "¿Cómo te sientes con tu sitio actual?", options: ["Me encanta", "Está bien", "Necesita mejoras", "Quiero uno nuevo", "Aún no tengo"] },
    instagram: { label: "Instagram", placeholder: "@usuario o enlace" },
    facebook: { label: "Facebook", placeholder: "Nombre de página o enlace" },
    tiktok: { label: "TikTok", placeholder: "@usuario o enlace" },
    youtube: { label: "YouTube", placeholder: "Enlace del canal" },
    linkedin: { label: "LinkedIn", placeholder: "Perfil o enlace de empresa" },
    google_business: { label: "Perfil de Empresa en Google", options: ["Sí — reclamado & activo", "Sí — pero descuidado", "No", "No estoy seguro"] },
    reviews_status: { label: "¿Aproximadamente cuántas reseñas & qué calificación?", placeholder: "ej. 45 reseñas, 4.8 estrellas en Google" },
    social_logins: { label: "Accesos de redes sociales (para publicar & gestionar por ti)", options: ["Plataforma (ej. Instagram)", "Correo o usuario", "Contraseña"], placeholder: "Agregar una cuenta", help: "Opcional & privado — solo si quieres que manejemos tus cuentas. Guardado de forma segura y nunca compartido." },
    media_files: { label: "Sube fotos o videos de tu producto / servicio", help: "Opcional — arrastra & suelta o busca" },
    media_links: { label: "O pega enlaces a tu contenido", placeholder: "Google Drive, Dropbox, etc.", help: "💡 Consejo: crea una carpeta en Google Drive, sube TODAS las fotos y videos de tu negocio y pega el enlace para compartir aquí. Entre más tengamos, más fuerte será tu marketing." },
    logo_files: { label: "Sube los archivos de tu logo", help: "Opcional — PNG, SVG, AI, etc." },
    brand_colors: { label: "Colores de marca", options: ["Principal", "Secundario", "Acento", "Color 4", "Color 5"], placeholder: "Agregar color", help: "Opcional — toca un recuadro o pega tus códigos hex. ¿No sabes? Creamos la paleta por ti." },
    brand_fonts: { label: "Tipografías que usas", placeholder: "ej. Montserrat, Georgia (opcional)" },
    hc_project_types: { label: "¿Qué tipos de proyectos haces?", options: ["Residencial", "Comercial", "Obra nueva", "Remodelaciones", "Reparaciones / servicio"] },
    hc_project_value: { label: "Valor típico de un proyecto", options: ["Menos de $1k", "$1k–$10k", "$10k–$50k", "$50k–$250k", "$250k+"] },
    hc_licensed: { label: "¿Estás licenciado & asegurado?" },
    hc_radius: { label: "¿Hasta dónde viajas para trabajar?", placeholder: "ej. 80 km desde Somerville" },
    fr_cuisine: { label: "¿Qué tipo de comida sirves?", placeholder: "ej. italiana a la leña" },
    fr_service: { label: "¿Cómo reciben tu comida los clientes?", options: ["En el local", "Para llevar", "Delivery", "Catering", "Food truck"] },
    fr_menu_url: { label: "Enlace a tu menú", placeholder: "https://" },
    fr_online_ordering: { label: "¿Ofreces pedidos en línea?" },
    re_products: { label: "¿Qué productos vendes?", placeholder: "Tus principales categorías" },
    re_platform: { label: "¿Dónde vendes en línea?", options: ["Shopify", "WooCommerce", "Etsy", "Amazon", "Solo redes sociales", "Aún no en línea", "Otro"] },
    re_aov: { label: "Valor promedio de pedido", options: ["Menos de $25", "$25–$75", "$75–$200", "$200+"] },
    re_instore: { label: "¿También tienes tienda física?" },
    ps_services: { label: "¿Qué servicios ofreces?", placeholder: "Lista tus principales servicios" },
    ps_clients: { label: "¿Quiénes son tus clientes?", options: ["Consumidores (B2C)", "Empresas (B2B)", "Ambos"] },
    ps_appointments: { label: "¿Tu negocio funciona con citas?" },
    ps_certs: { label: "Certificaciones o credenciales", placeholder: "Algo que genere confianza" },
    hw_services: { label: "¿Qué tratamientos o servicios ofreces?", placeholder: "Lista tus principales ofertas" },
    hw_booking: { label: "¿Cómo reservan los clientes?", options: ["Sistema de reserva en línea", "Llamada / texto", "Sin cita", "Una mezcla"] },
    hw_practitioners: { label: "¿Cuántos profesionales?", options: ["Solo yo", "2–5", "6–10", "10+"] },
    hw_memberships: { label: "¿Ofreces membresías o paquetes?" },
    rs_type: { label: "¿En qué te enfocas?", options: ["Residencial", "Comercial", "Alquileres", "Terrenos", "Administración de propiedades"] },
    rs_market: { label: "¿Qué mercado atiendes?", placeholder: "ej. condos de lujo en Miami-Dade" },
    rs_brokerage: { label: "Nombre de la inmobiliaria / equipo", placeholder: "Si aplica" },
    fn_mission: { label: "¿Cuál es tu misión?", placeholder: "Lo que haces y a quién sirves" },
    fn_size: { label: "¿Qué tan grande es tu comunidad?", options: ["Menos de 50", "50–200", "200–500", "500–1,000", "1,000+"] },
    fn_events: { label: "¿Organizas eventos con regularidad?" },
    fn_donations: { label: "¿Recibes donaciones en línea?" },
    ev_types: { label: "¿Qué tipos de eventos organizas?", placeholder: "ej. conciertos, conferencias, festivales" },
    ev_frequency: { label: "¿Con qué frecuencia?", options: ["Una vez", "Mensual", "Trimestral", "Anual", "Continuo / varios"] },
    ev_ticketing: { label: "¿Vendes boletos en línea?" },
    ot_describe: { label: "Cuéntanos sobre tu negocio", placeholder: "Describe lo que haces para poder ayudarte" },
    primary_goal: { label: "¿Cuál es tu objetivo #1 ahora?", options: ["Más leads & llamadas", "Reconocimiento de marca", "Ventas en línea", "Más tráfico al local", "Rebrand / renovación", "Lanzar algo nuevo"] },
    ideal_customer: { label: "Describe a tu cliente ideal", placeholder: "¿Quiénes son, dónde están, qué les importa?" },
    budget: { label: "Presupuesto mensual de marketing", options: ["Aún no sé", "Menos de $1k", "$1k–$3k", "$3k–$5k", "$5k–$10k", "$10k+"] },
    current_marketing: { label: "¿Qué marketing haces ahora?", options: ["Nada aún", "Redes sociales", "Anuncios pagos", "SEO", "Email", "Referencias / boca a boca"] },
    challenge_options: { label: "¿Cuál es tu mayor desafío ahora?", options: ["Pocos leads o llamadas", "Ventas inconsistentes", "Poco reconocimiento de marca", "Presencia online débil", "Sitio web desactualizado o inexistente", "No apareces en Google", "Perdiendo ante la competencia", "Sin clientes recurrentes", "Precios & márgenes", "Contratación & personal", "Crecimiento & escala", "Reseñas & reputación"] },
    biggest_challenge: { label: "¿Algo más que te esté frenando?", placeholder: "Cuéntanos con tus palabras (opcional)" },
    competitors: { label: "Competidores que admiras", placeholder: "Nombre o enlace", help: "Agrega hasta 5 — ayuda a comparar" },
    timeline: { label: "¿Qué tan pronto quieres empezar?", options: ["Lo antes posible", "1–3 meses", "3–6 meses", "Solo explorando"] },
    success_options: { label: "¿Cómo se ve el éxito en 6 meses?", options: ["Duplicar mis leads", "Ventas mensuales consistentes", "Agenda llena", "Una marca reconocida", "Nº 1 en Google en mi zona", "Más reseñas de 5 estrellas", "Más seguidores", "Lanzar algo nuevo", "Contratar más personal", "Abrir una nueva ubicación", "Marketing en automático", "Más tiempo libre"] },
    success_vision: { label: "¿Algo más? Describe tu resultado ideal", placeholder: "Píntanos el panorama (opcional)" },
    services_interested: { label: "¿Qué es lo que más te interesa?", options: ["Marca & Logo", "Sitio Web", "Anuncios Pagos", "Redes Sociales", "SEO", "CRM & Automatización", "Mentoría de Negocio", "App Móvil"] },
    anything_else: { label: "¿Algo más que debamos saber?", placeholder: "Opcional — el espacio es tuyo" },
    // ── paquete de lanzamiento ──
    want_package: { label: "¿Quieres que manejemos todo tu lanzamiento en un solo paquete?" },
    pkg_colors: { label: "Colores de marca que te gustarían", placeholder: "ej. azul marino & dorado — o 'ayúdame a elegir'" },
    pkg_logo_have: { label: "¿Ya tienes un logo que te encanta?" },
    pkg_logo_files: { label: "Sube tu logo o cualquier inspiración", help: "Opcional — logo actual, bocetos o estilos que te gusten" },
    pkg_logo_likes: { label: "Logos o marcas cuyo estilo admiras", placeholder: "Nombres o enlaces — ayuda a acertar el estilo" },
    pkg_instagram_handle: { label: "Usuario de Instagram que te gustaría", placeholder: "@tunegocio (verificamos disponibilidad)" },
    pkg_domain: { label: "Dominio del sitio que te gustaría", placeholder: "tunegocio.com" },
    pkg_cards_people: { label: "¿Quién necesita tarjeta de presentación?", placeholder: "Agregar persona", help: "Agrega a cada dueño o empleado que necesite tarjeta", options: ["Nombre", "Cargo / Rol", "Teléfono", "Correo"] },
  },
  review: {
    title: "¡Casi listo!",
    subtitle: "Esto es todo lo que compartiste. Toca cualquier paso para editar.",
    consent: "Acepto ser contactado por 360 For Business sobre mi estrategia de marketing.",
    edit: "Editar",
    empty: "Sin responder",
  },
  done: {
    title: "Gracias — ¡lo tenemos!",
    body: "Nuestro equipo está revisando tus respuestas y se comunicará dentro de 24 horas con el primer adelanto de tu estrategia de marketing personalizada.",
    cta: "Volver al inicio",
  },
  package: {
    introTitle: "Todo lo que necesitas para lanzar — hecho por nosotros",
    introBody: "Un paquete, un equipo, una marca coherente. Esto es lo que incluye:",
    includes: [
      "Sitio Web Profesional",
      "Configuración & Branding de Instagram",
      "CRM & Automatización en GoHighLevel",
      "Diseño de Logo",
      "Identidad de Marca Completa",
      "Tarjetas de Presentación para tu Equipo",
    ],
    addPerson: "Agregar otra persona",
  },
};

const content: Record<Locale, IntakeContent> = { en, pt, es };

export function getIntakeContent(locale: Locale): IntakeContent {
  return content[locale] ?? en;
}
